# P20 Implemening Logistic Regression by vertectization
For Logistic regression:

$ z = w^T x + b$ 

$\hat{y} = a = \sigma(z) = {{1} \over { 1 + e^{-z}}}$

L为log单调 ， 因目标为最小化loss, 所以为-log 

$L(a, y) = -(y log(a) + (1 - y)log(a-1))$

$J(w, b) ={{1} \over {m}} \sum_{i=1}^m{L(\hat{y}^{(i)}, y^{(i)})}  = - {{1} \over {m}} \sum_{i=1}^m  y^{(i)} log(\hat{y}^{(i)}  + (1- y^{(i)}) log(1- \hat{y}^{(i)})$

$  \frac{dJ}{da} = \frac{1}{m}(\frac{y}{a} - \frac{1-y}{1-a})$

$  \frac{dJ}{dz} =  \frac{dJ}{da}\frac{da}{dz} = (\frac{1}{m}(\frac{y}{a} - \frac{1-y}{1-a})) * a (1-a)  = \frac{1}{m}( y - a)$

$ \frac{dJ}{dw} = x dz = x ( \frac{1}{m}( y - a)) $

$ \frac{dJ}{db} = dz =  \frac{1}{m}( y - a)$

In [44]:
J = 0
W = np.random.randint(3, size = (1, 2))
b = 0
X = np.random.randint(10, size = (1, 2))
Y = np.array([1, 1])
m = 2
alpha = 0.1

def sigmoid(z):
    return 1/(1 + np.exp(-z))
    
for iterate in range(2):
    Z = np.dot(W.T, X) + b
    A = sigmoid(Z)
    dz = A - Y
    dw = (1/m) * X * dz.T
    db = 1 /m * np.sum(dz)
    print(W, dw)
    W = W - alpha * dw
    b = b - alpha * db

[[2 0]] [[-1.84325238e-05 -1.50000000e+00]
 [-1.84325238e-05 -1.50000000e+00]]


ValueError: shapes (2,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

# P21 Broadcast

In [2]:
import numpy as np

In [9]:
# 1
s = [[56.0, 0.0, 4.4, 68.0], [1.2, 104, 52, 8], [1.8, 135, 99, 0.9]]
A = np.array(s)
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [10]:
percentage = 100 * A/cal.reshape(1, 4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [19]:
# 2
a = np.random.randint(5, size = (2, 3) )
b = np.random. randint(100, size = (1, 3))
print(a)
print(b)
print(a + b)

[[3 4 4]
 [3 0 0]]
[[21 18 41]]
[[24 22 45]
 [24 18 41]]


In [20]:
# 3
a = np.random.randint(5, size = (2, 3) )
b = np.random. randint(100, size = (2, 1))
print(a)
print(b)
print(a + b)

[[4 1 2]
 [0 2 3]]
[[74]
 [18]]
[[78 75 76]
 [18 20 21]]


In [21]:
# 3
a = np.random.randint(5, size = (2, 3) )
b = np.random. randint(100, size = (2, 2))
print(a)
print(b)
print(a + b)

[[2 2 0]
 [2 4 2]]
[[18 54]
 [31 73]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

# P22 

In [50]:
a = np.random.randn(5)
print(a)
print(a.shape)
print(a.T)
print(np.dot(a, a.T))

[-0.16889368 -0.18007269 -1.0247917   0.03984615  0.46998805]
(5,)
[-0.16889368 -0.18007269 -1.0247917   0.03984615  0.46998805]
1.3336257570415297


In [55]:
a = np.random.randn(5, 1)
print(a)
print(a.shape)
print(a.T)
print(np.dot(a, a.T))
assert(a.shape) == ((5, 1))

[[ 0.92429526]
 [-0.72783215]
 [ 0.12517121]
 [ 0.65931123]
 [-1.86362315]]
(5, 1)
[[ 0.92429526 -0.72783215  0.12517121  0.65931123 -1.86362315]]
[[ 0.85432173 -0.6727318   0.11569516  0.60939825 -1.72253804]
 [-0.6727318   0.52973964 -0.09110363 -0.47986791  1.35640484]
 [ 0.11569516 -0.09110363  0.01566783  0.08252679 -0.23327197]
 [ 0.60939825 -0.47986791  0.08252679  0.4346913  -1.22870768]
 [-1.72253804  1.35640484 -0.23327197 -1.22870768  3.47309123]]
